### ISSUE TITLE
New profile directory issue

### ISSUE THREAD

**Issue by universish** [dr460nf1r3/firedragon-browser#114] opened 2024-09-10 14:31 UTC
I am using Fedora 40 OS. I had a non-default profile. I created a new profile, so I decided to delete my non-default profile. I deleted the profile with its files from about:profiles. But the profile's file was in /home/username/documents. It was not in a directory. It was using Documents as a directory. When I deleted the profile and its files, it also deleted Documents. I also had important documents and papers in Documents. They were deleted too. How will you compensate me now?
Why are newly created profiles not using this directory: /home/username/.var/app/org.garudalinux.firedragon/cache/firedragon  Why is it using the directory /home/username/documents. Why is it not using the directory /home/username/documents/firedragon ?
[bug]

**Comment by Technetium1** [comment] 2024-09-10 17:16
You must be using the flatpak. That is not expected behavior as you can see from my screenshot below. Please open an issue for it, linking the 2 issues you have already created: https://github.om/flathub/org.garudalinux.firedragon

I see you created another issue here, which could be related: https://github.com/dr460nf1r3/firedragon-browser/issues/113 . You may have corruption caused by the power outage.
![image](https://github.com/user-attachments/assets/d423ba9e-9317-4bfc-95a0-4ce367f34cd4)

**Comment by rkben** [comment] 2024-09-10 17:42
Can't recreate with Fedora 40
- Firedragon 11.18.1-1 Flatpak

Profiles default correctly to `~/.firedragon` and `~/.cache/firedragon`.

![image](https://github.com/user-attachments/assets/e5cb273d-f928-48f9-915b-2e6bfeef35d7)

Perhaps you accidentally set the profile directory to `~/Documents` instead of `~/Documents/$your_profile`.

**Comment by universish** [comment] 2024-09-11 05:55
Looking at about:profiles says that the files are in the location mentioned. but if you look in the Documents folder the files are there, they are not in the mentioned location. i checked, i checked 3 times.

Also the topic I opened before is completely independent of this topic. This problem happened at a completely different time. It has nothing to do with the power outage.

Secondly, I also asked about the deletion of my documents and who will compensate for the damage. please answer.

**Comment by dr460nf1r3** [comment] 2024-09-11 06:21
Well, I also tested the behavior locally and can't replicate the situation mentioned:

![image](https://github.com/user-attachments/assets/c87c145d-cf48-4ed2-9691-2be3a3427ff5)

> I had a non-default profile. I created a new profile, so I decided to delete my non-default profile. I deleted the profile with its files from about:profiles. But the profile's file was in /home/username/documents

Since you mentioned you created a non-default profile, I went ahead and tested the creation of a new profile:

![image](https://github.com/user-attachments/assets/cf305b0d-fb38-4078-8b51-67740e9a7ca2)

It is correctly created in the mentioned location:

![image](https://github.com/user-attachments/assets/f1e265c5-25b4-4aed-8bbb-a737ce40ded7)

Given the statements of the others and my own tests, I can't help but think you created this profile in the given location yourself. 



> Secondly, I also asked about the deletion of my documents and who will compensate for the damage. please answer.

While I really feel sorry for this happening, this won't be happening. 

1) It is free software without warranty included and 
2) we can't reconstruct the case in any way as outlined. 

I hate to be the person saying it, but this might be a good reminder to always keep backups of important data.

**Comment by rkben** [comment] 2024-09-11 06:22
> Looking at about:profiles says that the files are in the location mentioned. but if you look in the Documents folder the files are there, they are not in the mentioned location. i checked, i checked 3 times.

In my attempt to reproduce this issue; Firedragon did not create any files under `~/Documents`, unless I set the profile directory to it during profile creation. Under Fedora 40 Workstation without modification besides the flatpak installation of Firedragon.

> Secondly, I also asked about the deletion of my documents and who will compensate for the damage. please answer.

As with most software, by using Firedragon you agreed to it's license and forfeited certain rights, including that **you** accept responsibility for any malfunctions or potential damages caused by the software.
See section 6 and 7 of the license: https://github.com/dr460nf1r3/firedragon-browser/blob/master/LICENSE.txt#L263

If compensation is still something you wish to pursue then you should contact legal counsel, as such things are out of scope for Github issue threads.

**Comment by universish** [comment] 2024-09-18 08:00
the problem is with the firedragon flathub version. i moved the topic there. thanks for your reply

**Comment by universish** [comment] 2024-09-19 05:50
What I mean by compensation is this: who will return my lost and deleted files to me, who will recover them. Not money. Also, I did not mention anything legal. I already know what the license is and the content of the MIT license.

The other friend said "sadly": backup your important documents. Don't worry, my important documents are backed up on my encrypted disk, and also in 2 different encrypted cloud accounts. I am a cybersecurity expert, it is interesting that you say this.

The reason I opened the topic: there is a possibility that others will experience this problem. Because it is a serious problem.

Also, check the root folder of the firedragon profiles. There is no .firedragon directory, which is the root folder, in the specified location. It is in another location.

**Closed** 2024-09-19 05:50 UTC
