### ISSUE TITLE
FireDragon No longer works with KDE global menu after upgrade to 114

### ISSUE THREAD

**Issue by salperinlea** [dr460nf1r3/firedragon-browser#62] opened 2023-06-12 19:33 UTC
I've been using FireDragon since stock librewolf dropped the patch that allowed for dbus menu forwarding that KDE global menu uses. Unfortunately, firedragon no longer seems to either after an upgrade to 114. Reversion fixes this problem.

System is Arch running latest zen kernel, KDE frameworks 107, plasma 5.27.5, no nVIDIA, running firedragon through Xwayland.

**Comment by dr460nf1r3** [comment] 2023-06-12 19:55
Sadly, that's by choice (or not really). I could no longer find Ubuntu's appmenu patches for 114 and it seems like they have stopped providing them on launchpad in favor of shipping Snap-only Firefox :( unless, of course, there is something I'm overlooking 👀

**Comment by dr460nf1r3** [comment] 2023-06-13 11:01
Well that's a repository I found myself while looking for the patch, sadly it's outdated and I don't see myself as knowledgeable enough to maintain this patch on my own.

**Comment by steviator** [comment] 2023-07-05 07:50
So essentially, support for Plasma desktop has been dropped. It might be nice to do something to alert users to that fact rather than having them find and obscure bug report to figure out that the whole reason this fork existed has basically evaporated. 

Switching to Brave instead, Perhaps you should change the name of this browser to Gnomedragon to make it more obvious that it's not compatible with Plasma.

 So long and thanks for all the fish.

**Comment by dr460nf1r3** [comment] 2023-07-05 08:40
I feel some kind of bitterness reading your comment. Incompatibility is essentially something else, the browser can still be used perfectly fine on KDE, it just does not feature the appmenu integration anymore, which is also only relevant to those people using making use of this KDE feature.

I'm still undecided whether I'm continuing the maintenance of this project, since I feel like a major part of what made it attractive to me doesn't exist anymore.

**Comment by salperinlea** [comment] 2023-07-05 14:52
Do older versions of the patch actually break anything with newer firefox?

**Comment by dr460nf1r3** [comment] 2023-07-06 17:29
The patch itself does only apply to a specific version and would need to be rebased against newer versions. However it's just a matter of time until something breaks which needs source code changes.

**Comment by Zastando** [comment] 2023-07-14 08:17
> I'm still undecided whether I'm continuing the maintenance of this project, since I feel like a major part of what made it attractive to me doesn't exist anymore.

So are you "only" missing the KDE global menu or is there something else which doesn't align with the original idea behind Firedragon anymore ?

**Comment by dr460nf1r3** [comment] 2023-07-14 09:05
Basically it's just the KDE global menu. After discussing this with a few people, someone has volunteered to help out with the maintenance so FireDragon will stay :)

**Comment by Zastando** [comment] 2023-07-14 15:16
This is great news, hopefully it works out as intended !

**Comment by dr460nf1r3** [comment] 2023-09-05 04:42
Closing this here since it can't be fixed. 
@Zastando our plan worked out btw 😸

**Closed** 2023-09-05 04:42 UTC
Labels: needs upstream fix

**Comment by stefanwimmer128** [comment] 2023-10-16 18:32
I found a working appmenu patch: https://gitlab.com/kylekern0/librewolf-kde-appmenu/-/blob/master/unity-menubar.patch?ref_type=heads

I already successfully integrated it into my own version of firedragon: https://git.stefanwimmer128.xyz/stefanwimmer128/firedragon-unsigned-extensions/-/commit/e5f6a92bf9945233c40452d69fef59bdbca1a355

**Comment by dr460nf1r3** [comment] 2023-10-19 12:04
Any experience with how well this one is maintained yet?

**Comment by Technetium1** [comment] 2023-10-19 13:36
@dr460nf1r3 send them mail since they don't exist on GitHub 👀 
https://gitlab.com/kylekern0/lp-solver/-/blob/master/LICENSE?ref_type=heads#L1
